name: Build and Package
  
permissions:
  contents: write

on:
  push:
    tags : 
      - '*'


jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Set up ENV 
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Installing Dependencies
      run : |
        sudo apt-get install libasound2-dev

    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build server 
      run: make build-server 

    - name: Build Client 
      run: make build-client

    - name: Generate Installer
      run: |
        chmod +x ./scripts/compile_installer.sh
        ./scripts/compile_installer.sh

    - name: Upload Installer Script
      id : upload-installer
      uses: actions/upload-artifact@v4
      with:
        name: installer-script
        path: ./bin/install.sh
    
    - name: Release Installer 
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        body: "Installer for version ${{ github.ref }}"
        draft: false
        prerelease: false
        name: "goplay-${{ env.RELEASE_VERSION}}"
        files: ./bin/install.sh
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Readme
      run: |
        chmod +x ./scripts/update_readme.sh
        ./scripts/update_readme.sh  $RELEASE_VERSION

    - name: Push changes 
      uses: mikeal/publish-to-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main

