name: Build and Package

on:
  push:
    branches:
      - main # Adjust this as needed

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Installing alsa 
      run : |
        sudo apt-get install libasound2-dev
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Build server 
      run: make build-server 

    - name: Build Client 
      run: make build-client

    - name: Generate Installer
      run: |
        chmod +x ./scripts/compile_installer.sh
        ./scripts/compile_installer.sh

    - name: Upload Installer Script
      id : upload-installer
      uses: actions/upload-artifact@v4
      with:
        name: installer-script
        path: ./bin/install.sh
    
    - name: Release Installer 
      uses: softprops/action-gh-release@v1
      with:
        # url: ${{ steps.upload-installer.outputs.artifact-url }}
        tag_name: ${{ github.ref }}
        token:  ${{ github.token }}
        body: "Installer for version ${{ github.ref }}"
        draft: false
        prerelease: false
        name: "Installer for version ${{ github.ref }}"
        files:
          ./bin/install.sh
        token: ${{ github.token }}
